FROM anapsix/alpine-java:8_server-jre_unlimited
MAINTAINER kirk77@gmail.com

###################################################
# openfire
###################################################

ENV OPENFIRE_VERSION=4_0_3 \
	DATA_DIR=/c/Users/kirk/docker_data

RUN wget http://www.igniterealtime.org/downloadServlet?filename=openfire/openfire_${OPENFIRE_VERSION}.tar.gz -O /openfire_${OPENFIRE_VERSION}.tar.gz \
&& tar -xvzf /openfire_${OPENFIRE_VERSION}.tar.gz \
&& mv openfire /opt/openfire \
&& rm -f openfire_${OPENFIRE_VERSION}.tar.gz

RUN echo "/opt/openfire/bin/openfire start" >> /start.sh
EXPOSE 3478/tcp 3479/tcp 5222/tcp 5223/tcp 5229/tcp 7070/tcp 7443/tcp 7777/tcp 9090/tcp 9091/tcp


###################################################
# mariadb
###################################################
ENV MYSQL_ROOT_PASSWORD=root123

RUN set -ex && \
    apk add --no-cache bash mariadb mariadb-client tzdata && \
    mkdir -p /run/mysqld && \
    chown mysql:mysql /run/mysqld && \
    sed -Ei -e 's/^(bind-address|log)/#&/' \
        -e 's/^\[mysqld\]$/&\nskip-host-cache\nskip-name-resolve\nuser=mysql/' /etc/mysql/my.cnf
RUN mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql

RUN echo "mysqld &" >> /start.sh && \
    echo "until (pidof mysqld)" >> /start.sh && \
    echo "	do" >> /start.sh && \
    echo "		sleep 1" >> /start.sh && \
    echo "	done" >> /start.sh

EXPOSE 3306/tcp

###################################################
# rabbitmq
###################################################
ENV RABBITMQ_VERSION=3.6.1 \
    RABBITMQ_AUTOCLUSTER_PLUGIN_VERSION=0.4.1 \
	RABBITMQ_AUTOCLUSTER_URL=https://github.com/aweber/rabbitmq-autocluster/releases/download/${RABBITMQ_AUTOCLUSTER_PLUGIN_VERSION}/autocluster-${RABBITMQ_AUTOCLUSTER_PLUGIN_VERSION}.ez \
	PKG_NAME=rabbitmq \
	RABBITMQ_HOME=/opt/rabbitmq \
	RABBITMQ_MNESIA_BASE=/var/lib/rabbitmq \
    RABBITMQ_URL=https://www.rabbitmq.com/releases/rabbitmq-server/v${RABBITMQ_VERSION}/rabbitmq-server-generic-unix-${RABBITMQ_VERSION}.tar.xz \
	PATH=${PATH}:${RABBITMQ_HOME}/sbin \
	RABBITMQ_ENABLED_PLUGINS_FILE=${RABBITMQ_HOME}/etc/rabbitmq/enabled_plugins
	
# Copy Files 
# COPY ssl.config ${RABBITMQ_HOME}/etc/rabbitmq/ 
# COPY standard.config /srv/rabbitmq_server-${RABBITMQMQ_VERSION}/etc/rabbitmq/ 
# COPY wrapper.sh /usr/bin/wrapper 

# Download RabbitMQ 
# RUN chmod a+x /usr/bin/wrapper &&

RUN apk add --update curl tar xz bash && \
	echo "http://dl-4.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
	echo "http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
	echo "http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
	apk add erlang erlang erlang-mnesia erlang-public-key erlang-crypto erlang-ssl \
		erlang-sasl erlang-asn1 erlang-inets erlang-os-mon erlang-xmerl erlang-eldap \
		erlang-syntax-tools --update-cache --allow-untrusted
RUN	mkdir -p ${RABBITMQ_HOME} && \
	curl -o /opt/${PKG_NAME}.tar.xz ${RABBITMQ_URL}
RUN	tar -xf /opt/${PKG_NAME}.tar.xz --strip-components=1 -C ${RABBITMQ_HOME} && \
	rm -f /opt/${PKG_NAME}.tar.xz && \
	touch ${RABBITMQ_ENABLED_PLUGINS_FILE} && \
	curl -L -o ${RABBITMQ_HOME}/plugins/autocluster-${RABBITMQ_AUTOCLUSTER_PLUGIN_VERSION}.ez ${RABBITMQ_AUTOCLUSTER_URL} && \
	rabbitmq-plugins enable --offline rabbitmq_management && \
	# rabbitmq-plugins enable --offline autocluster && \
	#apk del --purge tar xz &&
	rm -Rf /var/cache/apk/* && \
    ln -sf ${RABBITMQ_HOME} /rabbitmq

EXPOSE      5671/tcp 5672/tcp 15672/tcp 15671/tcp

###################################################  
VOLUME ["${DATA_DIR}"]

RUN chmod 755 /start.sh
CMD ["/start.sh && bash"]
